const defaultProjects=[{id:1,name:"Campus Event Management System",description:"A web application for managing college events, registrations and student participation.",category:"Web Development",skills:["HTML","CSS","JavaScript"],teamSize:4,ownerEmail:"demo@campusconnect.com",members:[]},{id:2,name:"AI Study Assistant",description:"A student assistant that helps organize study material and learning tasks.",category:"Artificial Intelligence",skills:["Python","AI","Machine Learning"],teamSize:4,ownerEmail:"demo@campusconnect.com",members:[]},{id:3,name:"Cyber Security Awareness Portal",description:"A portal that teaches students about phishing, passwords and safe online practices.",category:"Cyber Security",skills:["HTML","JavaScript","Cyber Security"],teamSize:3,ownerEmail:"demo@campusconnect.com",members:[]}];

function getStudents(){return JSON.parse(localStorage.getItem("cc_students"))||[]}
function saveStudents(x){localStorage.setItem("cc_students",JSON.stringify(x))}
function getProjects(){let x=localStorage.getItem("cc_projects");if(!x){localStorage.setItem("cc_projects",JSON.stringify(defaultProjects));return defaultProjects}return JSON.parse(x)}
function saveProjects(x){localStorage.setItem("cc_projects",JSON.stringify(x))}
function getCurrentUser(){return JSON.parse(localStorage.getItem("cc_currentUser"))}
function setCurrentUser(x){localStorage.setItem("cc_currentUser",JSON.stringify(x))}
function logout(){localStorage.removeItem("cc_currentUser");location.href="login.html"}
function requireLogin(){const u=getCurrentUser();if(!u){location.href="login.html";return null}return u}

function createDemoStudent(){const s=getStudents();if(!s.some(x=>x.email==="demo@campusconnect.com")){s.push({id:1,name:"Demo Student",roll:"CC001",email:"demo@campusconnect.com",password:"demo123",college:"CampusConnect College",branch:"CSE",year:"3rd Year",skills:["Python","Java","HTML","CSS"],about:"Computer Science student interested in software development."});saveStudents(s)}}

document.addEventListener("DOMContentLoaded",()=>{createDemoStudent();const p=location.pathname;if(p.endsWith("dashboard.html"))loadDashboard();if(p.endsWith("projects.html")){requireLogin();renderProjects();document.getElementById("projectForm")?.addEventListener("submit",createProject)}if(p.endsWith("students.html")){requireLogin();renderStudents()}if(p.endsWith("profile.html"))loadProfile();document.getElementById("loginForm")?.addEventListener("submit",loginUser);document.getElementById("registerForm")?.addEventListener("submit",registerUser);document.getElementById("profileForm")?.addEventListener("submit",updateProfile)});

function registerUser(e){e.preventDefault();const s=getStudents(),email=document.getElementById("regEmail").value.trim().toLowerCase(),m=document.getElementById("registerMessage");if(s.some(x=>x.email===email)){m.style.color="#dc2626";m.textContent="An account with this email already exists.";return}const u={id:Date.now(),name:document.getElementById("regName").value.trim(),roll:document.getElementById("regRoll").value.trim(),email,password:document.getElementById("regPassword").value,college:document.getElementById("regCollege").value.trim(),branch:document.getElementById("regBranch").value,year:document.getElementById("regYear").value,skills:document.getElementById("regSkills").value.split(",").map(x=>x.trim()).filter(Boolean),about:""};s.push(u);saveStudents(s);m.style.color="#16a34a";m.textContent="Registration successful! Redirecting to login...";setTimeout(()=>location.href="login.html",1000)}

function loginUser(e){e.preventDefault();const email=document.getElementById("loginEmail").value.trim().toLowerCase(),pass=document.getElementById("loginPassword").value,m=document.getElementById("loginMessage"),u=getStudents().find(x=>x.email===email&&x.password===pass);if(!u){m.style.color="#dc2626";m.textContent="Invalid email or password.";return}setCurrentUser(u);m.style.color="#16a34a";m.textContent="Login successful!";setTimeout(()=>location.href="dashboard.html",500)}

function loadDashboard(){const u=requireLogin();if(!u)return;document.getElementById("welcomeName").textContent=u.name;const p=getProjects();document.getElementById("myProjectCount").textContent=p.filter(x=>x.ownerEmail===u.email).length;document.getElementById("joinedCount").textContent=p.filter(x=>(x.members||[]).includes(u.email)).length;document.getElementById("studentCount").textContent=getStudents().length;document.getElementById("totalProjectCount").textContent=p.length;document.getElementById("dashboardProjects").innerHTML=p.slice(-3).reverse().map(projectCardHTML).join("")||'<div class="empty-state">No projects available.</div>';document.getElementById("dashboardSkills").innerHTML=(u.skills||[]).map(x=>`<span class="badge">${esc(x)}</span>`).join("")||"<p>No skills added yet.</p>"}

function projectCardHTML(p){const u=getCurrentUser(),joined=u&&(p.members||[]).includes(u.email),owner=u&&p.ownerEmail===u.email;return `<div class="project-card"><span class="badge">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><p><strong>Skills:</strong> ${p.skills.map(esc).join(", ")}</p><p><strong>Team Size:</strong> ${p.teamSize}</p><div class="card-buttons">${owner?`<button class="delete-btn" onclick="deleteProject(${p.id})">Delete</button>`:`<button class="join-btn" onclick="joinProject(${p.id})" ${joined?"disabled":""}>${joined?"Joined ✓":"Join Project"}</button>`}</div></div>`}

function renderProjects(){const b=document.getElementById("projectList");if(!b)return;const q=(document.getElementById("projectSearch")?.value||"").toLowerCase();const p=getProjects().filter(x=>[x.name,x.description,x.category,...x.skills].join(" ").toLowerCase().includes(q));b.innerHTML=p.map(projectCardHTML).join("")||'<div class="empty-state">No matching projects found.</div>'}
function openProjectForm(){document.getElementById("projectModal").classList.remove("hidden")}
function closeProjectForm(){document.getElementById("projectModal").classList.add("hidden")}

function createProject(e){e.preventDefault();const u=requireLogin();if(!u)return;const p={id:Date.now(),name:document.getElementById("projectName").value.trim(),description:document.getElementById("projectDescription").value.trim(),category:document.getElementById("projectCategory").value,skills:document.getElementById("projectSkills").value.split(",").map(x=>x.trim()).filter(Boolean),teamSize:Number(document.getElementById("projectTeamSize").value),ownerEmail:u.email,members:[]};const all=getProjects();all.push(p);saveProjects(all);document.getElementById("projectForm").reset();closeProjectForm();renderProjects();const m=document.getElementById("projectMessage");m.style.color="#16a34a";m.textContent="Project created successfully!";setTimeout(()=>m.textContent="",2000)}

function joinProject(id){const u=requireLogin();if(!u)return;const p=getProjects(),x=p.find(a=>a.id===id);if(!x)return;x.members=x.members||[];if(x.members.includes(u.email))return;if(x.members.length>=x.teamSize-1){alert("This project has reached its team size.");return}x.members.push(u.email);saveProjects(p);renderProjects();alert("You joined the project successfully!")}
function deleteProject(id){const u=requireLogin();if(!u)return;const p=getProjects(),x=p.find(a=>a.id===id);if(!x||x.ownerEmail!==u.email)return;if(!confirm("Are you sure you want to delete this project?"))return;saveProjects(p.filter(a=>a.id!==id));renderProjects()}

function renderStudents(){const b=document.getElementById("studentList");if(!b)return;const q=(document.getElementById("studentSearch")?.value||"").toLowerCase();const s=getStudents().filter(x=>[x.name,x.roll,x.college,x.branch,x.year,...(x.skills||[])].join(" ").toLowerCase().includes(q));b.innerHTML=s.map(x=>`<div class="student-card"><div class="avatar" style="width:60px;height:60px;font-size:24px;margin:0 0 15px">${esc(x.name.charAt(0).toUpperCase())}</div><h3>${esc(x.name)}</h3><p><strong>Roll No:</strong> ${esc(x.roll)}</p><p><strong>Branch:</strong> ${esc(x.branch)} | ${esc(x.year)}</p><p><strong>College:</strong> ${esc(x.college)}</p><p><strong>Email:</strong> ${esc(x.email)}</p><div>${(x.skills||[]).map(k=>`<span class="badge">${esc(k)}</span>`).join("")}</div></div>`).join("")||'<div class="empty-state">No students found.</div>'}

function loadProfile(){const u=requireLogin();if(!u)return;document.getElementById("profileName").value=u.name||"";document.getElementById("profileRoll").value=u.roll||"";document.getElementById("profileEmail").value=u.email||"";document.getElementById("profileCollege").value=u.college||"";document.getElementById("profileBranch").value=u.branch||"CSE";document.getElementById("profileYear").value=u.year||"3rd Year";document.getElementById("profileSkills").value=(u.skills||[]).join(", ");document.getElementById("profileAbout").value=u.about||"";updateProfileCard(u)}
function updateProfile(e){e.preventDefault();const u=requireLogin();if(!u)return;const s=getStudents(),i=s.findIndex(x=>x.email===u.email);if(i<0)return;const n={...s[i],name:document.getElementById("profileName").value.trim(),roll:document.getElementById("profileRoll").value.trim(),email:document.getElementById("profileEmail").value.trim().toLowerCase(),college:document.getElementById("profileCollege").value.trim(),branch:document.getElementById("profileBranch").value,year:document.getElementById("profileYear").value,skills:document.getElementById("profileSkills").value.split(",").map(x=>x.trim()).filter(Boolean),about:document.getElementById("profileAbout").value.trim()};s[i]=n;saveStudents(s);setCurrentUser(n);updateProfileCard(n);const m=document.getElementById("profileMessage");m.style.color="#16a34a";m.textContent="Profile updated successfully!"}
function updateProfileCard(u){document.getElementById("profileAvatar").textContent=(u.name||"S").charAt(0).toUpperCase();document.getElementById("profileNameCard").textContent=u.name||"Student";document.getElementById("profileBranchCard").textContent=`${u.branch||""} | ${u.year||""}`;document.getElementById("profileCollegeCard").textContent=u.college||""}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}